### ISSUE TITLE
Sisyphus forgot how to speak

### ISSUE THREAD

**Issue by kierkat10** [ImNotSimon/LowTierSisyphus#3]
The intro now makes no sound...

(yes i tested it without any other mods as well)

**Comment by ImNotSimon** [comment]
is there any error printed to the console? is the mod installed correctly - as in, LowTierSisyphus.dll is alongside the "lowtiersisy" assetbundle file? since Sisyphus being quiet usually means that the mod, somehow, fails to load the file from the assetbundle

**Comment by kierkat10** [comment]
time to test

**Comment by kierkat10** [comment]
what the fuck he speaks now

**Comment by kierkat10** [comment]
aww his first words were "You are a worthless bitchass machine" 🥰🥰🥰
